### ISSUE TITLE
Source Code?

### ISSUE THREAD

**Issue by luuuyi** [openseg-group/openseg.pytorch#1]
Hello, would you like share your source code?

**Comment by WeihongM** [comment]
@PkuRainBow

**Comment by qiulesun** [comment]
@PkuRainBow  In Fig. 7, you show the learned attention maps. I hold the view that it it very meaningful and helpful for understanding the proposed method. Could you provide more details about how to implement it or share the code to implement it?

**Comment by PkuRainBow** [comment]
@luuuyi @qiulesun We have released the source code.
