### ISSUE TITLE
SegFix paper link

### ISSUE THREAD

**Issue by davidblom603** [openseg-group/openseg.pytorch#11]
Hi!

Thanks for your nice work. It is really impressive. I'm interested in the SegFix algorithm.
Could you send a copy of the paper "SegFix: Model-Agnostic Boundary Refinement for Segmentation", since I cannot find it on arXiv.

Best,
David

**Comment by PkuRainBow** [comment]
Thanks for your interest in our work and we plan to release the paper to arXiv in the future months.

We would like to recommend you to use the SegFix offset files to improve your results on Cityscapes semantic/instance segmentation tasks.

**Comment by swjtulinxi** [comment]
![image](https://user-images.githubusercontent.com/50089266/83208796-3a5d3580-a189-11ea-93d2-88269c873ffb.png)
你好，请问你论文的这些参数是用的的代码中，下面的代码做出来的吗，因为你每一个模块下，比如ocr、isa、oc等代码最后面都有下面这些代码，请问使用它来比较参数和内存和时间的吗
  def count_parameters(model):
        return sum(p.numel() for p in model.parameters() if p.requires_grad)

    avg_time = 0
    avg_mem  = 0
    import time
    with torch.no_grad():
        for i in range(100):
            start_time = time.time()
            outputs = conv_3x3(feats)
            outputs = baseoc_infer(outputs)
            torch.cuda.synchronize()
            avg_time += (time.time() - start_time)
            avg_mem  += (torch.cuda.max_memory_allocated()-feats.element_size() * feats.nelement())

    print("Average Parameters : {}".format(count_parameters(baseoc_infer)+count_parameters(conv_3x3)))
    print("Average Running Time: {}".format(avg_time/100))
    print("Average GPU Memory: {}".format(avg_mem/100))

**Comment by swjtulinxi** [comment]
![image](https://user-images.githubusercontent.com/50089266/83209025-d38c4c00-a189-11ea-8d0d-3475a28b5571.png)
请问你可视化这些过程中的张量是用的下面文件夹中的代码吗
![image](https://user-images.githubusercontent.com/50089266/83209068-f28ade00-a189-11ea-8a2d-6df07c161c09.png)

**Comment by swjtulinxi** [comment]
大佬，我不是质疑你的工作哈，我是感觉ocr和acfnet有一点点相似

**Comment by PkuRainBow** [comment]
@swjtulinxi ocr是2019年初的工作，最多是同时期工作。

**Comment by swjtulinxi** [comment]
好的，其实我有一个疑惑就是他为什么就能超过ocnet，如果前端一样哈，

**Comment by PkuRainBow** [comment]
他用ASPP做baseline了~

**Comment by swjtulinxi** [comment]
我是说ocrnet，在这里面其实已经没有用到non-local注意力的思想了，但反而精度还要高于ocnet，在acfnet中用了aspp做baseline才超过ocnet的，大佬你这里面是在前端直接加入ocr模块，就可以超过ocnet了
