### ISSUE TITLE
Test sets results

### ISSUE THREAD

**Issue by arashash** [openseg-group/openseg.pytorch#12]
For comparison in our paper, we are looking for the detailed test set results (class IoUs) of these prediction files that you shared: https://drive.google.com/drive/folders/156vMABydr7btdPDBU6b9J-e0jJHuPI73
Do you happen to have a snapshot of the submission results obtained with these predictions?
Thank you for your consideration.

**Comment by arashash** [comment]
![Screenshot from 2020-04-25 05-45-09](https://user-images.githubusercontent.com/15813444/80269863-186d2080-86bc-11ea-81de-66ee4773d80e.png)
Are these prediction files the same as the ones submitted to the first and last submissions in this snapshot?

**Comment by PkuRainBow** [comment]
@arashash Yes, it is the same. 

**hrnet_w48_ocr_b_hrnet48_8_20000_trainval_coarse_tr…llary_pretrain_freeze_bn_1_test_ms_6x_mIoU_842.zip** is the result w/o SegFix, which achieves 84.2 on Cityscapes test set.

**segfix_hrnet_w48_ocr_b_hrnet48_8_20000_trainval_co…llary_pretrain_freeze_bn_1_test_ms_6x_mIoU_845.zip**  is the result w/ SegFix, which achieves 84.5 on Cityscapes test set.

**Comment by arashash** [comment]
Awesome. but there is no submission with 84.2 on Cityscapes test set right now. is it because it's replaced? if so do you have the screenshot of its detailed results?

**Comment by arashash** [comment]
by the way, how should we cite these results? should we use this:
@article{yuan2020segfix,
  title={SegFix: Model-Agnostic Boundary Refinement for Segmentation},
  author={Yuan Yuhui and Xie Jingyi and Chen Xilin and Wang Jingdong},
  journal={arXiv preprint},
  year={2020}
}
or your earlier works?

**Comment by PkuRainBow** [comment]
Thanks. You might consider citing both OCR and SegFix like,

> @article{yuan2019ocr,
>   title={Object-Contextual Representations for Semantic Segmentation},
>   author={Yuan Yuhui and Chen Xilin and Wang Jingdong},
>   journal={arXiv preprint arXiv:1909.11065},
>   year={2019}
> }
> 
> @article{yuan2020segfix,
>   title={SegFix: Model-Agnostic Boundary Refinement for Segmentation},
>   author={Yuan Yuhui and Xie Jingyi and Chen Xilin and Wang Jingdong},
>   journal={arXiv preprint},
>   year={2020}
> }

**Comment by PkuRainBow** [comment]
![screencapture-cityscapes-dataset-method-details-2020-04-26-10_00_36](https://user-images.githubusercontent.com/4639578/80295387-db308d80-87a4-11ea-9164-bac87dcdbe62.png)

**Comment by arashash** [comment]
Fantastic. Thank you so much
