### ISSUE TITLE
Cityscapes Instance offsets

### ISSUE THREAD

**Issue by mohan1914** [openseg-group/openseg.pytorch#13]
Under the Cityscapes Semantic Segmentation section in model zoo following is written:
To apply SegFix, you should first down the offset files offset_instance.zip to $DATA_ROOT/cityscapes, and then extract the archive.

where offset_instance.zip is linked to offset_semantic.zip.

I was wondering whether you have released the instance offset and the link is wrong or it's just a typo?
In the case of a typo, can you provide the link for instance offsets?

**Comment by PkuRainBow** [comment]
@hsfzxjy Please check this issue.

**Comment by hsfzxjy** [comment]
Fixed. It's a typo. Thanks for feedback!
