### ISSUE TITLE
Guidelines on how to train the model your own dataset.

### ISSUE THREAD

**Issue by IemProg** [openseg-group/openseg.pytorch#14]
Could you please, improve the documentation about how can we use the library with pre-trained model  ?

I would like to use it on my own dataset if possible.
Thanks

**Comment by PkuRainBow** [comment]
@IemProg Thanks for your advice and we will improve the Doc.
 
Do you mean the details on how to train the models on your own dataset?

**Comment by IemProg** [comment]
Yeah, please, especially if the dataset is not in "Yaml" extension, I have dataset in JPG format.

Thanks !

**Comment by PkuRainBow** [comment]
@IemProg In fact, the dataset is not required to be "Yaml" extension, and JPG is totally OK.

_We illustrate an overall (coarse) guidelines on how to train the model on your own dataset as below and hope it helps._

- first of all, you need to create a set of config files under the folder **openseg.pytorch/configs/your_dataset_name** following the other dataset. For example, we take the coco_stuff as an example (as below), 

 https://github.com/openseg-group/openseg.pytorch/blob/db0d3894673015e9350881db2d02175b0a263368/configs/coco_stuff/R_101_D_8.json#L2-L49

You need to change a set of keywords in the json file including the "dataset", "num_classes", "label_list", "reduce_zero_label", "input_size","crop_size", "base_lr" and so on. Of course, you can also reset these parameters in the training script file (listed as below),

https://github.com/openseg-group/openseg.pytorch/blob/db0d3894673015e9350881db2d02175b0a263368/scripts/coco_stuff/run_h_48_d_4_ocr_train.sh#L31-L48 

- second, you need to organize your training/validation dataset following the folder structure like below,

```
├── your_dataset_name
│   ├── train
│   │   ├── image
│   │   └── label
│   ├── val
│   │   ├── image
│   │   └── label
```

- third, you need to prepare the training script following the example below and change the DATA_DIR, SAVE_DIR, CONFIGS, and all of the other settings accordingly.

https://github.com/openseg-group/openseg.pytorch/blob/db0d3894673015e9350881db2d02175b0a263368/scripts/coco_stuff/run_h_48_d_4_ocr_train.sh

**Comment by jhyin12** [comment]
It seems this is not suitable for training segfix on my own dataset
