### ISSUE TITLE
Guildline on How to use the Segfix method?

### ISSUE THREAD

**Issue by rorschach-xiao** [openseg-group/openseg.pytorch#15]
Could you please improve the doc about how to use the segfix method？I'm a little bit confused about how to generate the offset file.

**Comment by PkuRainBow** [comment]
We have illustrated how to use SegFix for the Cityscapes semantic seg/instance seg.  Please feel free to try the SegFix for your Cityscapes submission.

As for the details, please be patient and we will release the SegFix paper to the arXiv (latter) depending on the review comments.
