### ISSUE TITLE
resnet50 pretrained model

### ISSUE THREAD

**Issue by devolfnn** [openseg-group/openseg.pytorch#18]
Hi,

Would you consider releasing the resnet50 pretrained model?

**Comment by PkuRainBow** [comment]
Currently, we have no plan to train the OCNet series models based on ResNet-50. If you mean the ImageNet pre-trained checkpoints, please download from [here](http://sceneparsing.csail.mit.edu/model/pretrained_resnet/).

**Comment by qiulesun** [comment]
@PkuRainBow Both resnet50-imagenet.pth and resnet101-imagenet.pth you provide, which the first 7x7 conv. is replaced with 3 3x3 ones and dilation rates are set to 2 and 4 for last two stages, are trained from scratch on ImageNet-1K?

**Comment by PkuRainBow** [comment]
We should make the same modifications for both resnet50 and resnet101.

**Comment by qiulesun** [comment]
@PkuRainBow 
For resnet50-imagenet.pth and resnet101-imagenet.pth，you train them using all above three strategies ?

**Comment by PkuRainBow** [comment]
We have not trained & reported any results based on resnet-50.  We suggest making the modifications if you plan to use resnet-50.

**Comment by qiulesun** [comment]
@PkuRainBow 
The backbone model resnet101-imagenet.pth you used need to be trained from scratch on ImageNet-1K.
When train it, you adopt all above three strategies ?
