### ISSUE TITLE
Error in loading the checking point for validation (Cityscapes, both ResNet-101 and HRNet-W48)

### ISSUE THREAD

**Issue by iamimage** [openseg-group/openseg.pytorch#20]
Dear Author,

I am trying to use the pretrained models (ResNet-101 or HRNet-W48 backbones) in my work, but similar errors are reported for both backbones. 

1. checkpoint names:
checkpoints/cityscapes/hrnet_w48_ocr_1_latest.pth
checkpoints/cityscapes/spatial_ocrnet_deepbase_resnet101_dilated8_1_latest.pth

2. commands: 
(for **HRNet-W48**:)
python -u main.py --configs configs/cityscapes/H_48_D_4.json --drop_last y --backbone hrnet48 --model_name hrnet_w48_ocr --checkpoints_name hrnet_w48_ocr_1 --phase test --gpu 0 --resume ./checkpoints/cityscapes/hrnet_w48_ocr_1_latest.pth --loss_type fs_auxce_loss --test_dir input_images --out_dir output_images
(for **ResNet101**:)
python -u main.py --configs configs/cityscapes/R_101_D_8.json --drop_last y --backbone deepbase_resnet101_dilated8 --model_name spatial_ocrnet --checkpoints_name spatial_ocrnet_deepbase_resnet101_dilated8_1 --phase test --gpu 0  --resume ./checkpoints/cityscapes/spatial_ocrnet_deepbase_resnet101_dilated8_1_latest.pth --loss_type fs_auxce_loss --test_dir input_images --out_dir output_images

3. environments:
python                    3.7.3                h33d41f4_1    conda-forge
pytorch                   1.1.0           py3.7_cuda10.0.130_cudnn7.5.1_0    PyTorch
torchcontrib              0.0.2                     <pip>
torchvision               0.3.0           py37_cu10.0.130_1    pytorch
gcc (GCC) 7.2.0
cuda 10.0

4. Error messages: 
RuntimeError: unexpected key in source state_dict: conv_3x3.1.weight, conv_3x3.1.bias, conv_3x3.1.running_mean, conv_3x3.1.running_var, spatial_ocr_head.object_context_block.f_pixel.1.weight, spatial_ocr_head.object_context_block.f_pixel.1.bias, spatial_ocr_head.object_context_block.f_pixel.1.running_mean, spatial_ocr_head.object_context_block.f_pixel.1.running_var, spatial_ocr_head.object_context_block.f_pixel.3.weight, spatial_ocr_head.object_context_block.f_pixel.3.bias, spatial_ocr_head.object_context_block.f_pixel.3.running_mean, spatial_ocr_head.object_context_block.f_pixel.3.running_var, spatial_ocr_head.object_context_block.f_object.1.weight, spatial_ocr_head.object_context_block.f_object.1.bias, spatial_ocr_head.object_context_block.f_object.1.running_mean, spatial_ocr_head.object_context_block.f_object.1.running_var, spatial_ocr_head.object_context_block.f_object.3.weight, spatial_ocr_head.object_context_block.f_object.3.bias, spatial_ocr_head.object_context_block.f_object.3.running_mean, spatial_ocr_head.object_context_block.f_object.3.running_var, spatial_ocr_head.object_context_block.f_down.1.weight, spatial_ocr_head.object_context_block.f_down.1.bias, spatial_ocr_head.object_context_block.f_down.1.running_mean, spatial_ocr_head.object_context_block.f_down.1.running_var, spatial_ocr_head.object_context_block.f_up.1.weight, spatial_ocr_head.object_context_block.f_up.1.bias, spatial_ocr_head.object_context_block.f_up.1.running_mean, spatial_ocr_head.object_context_block.f_up.1.running_var, spatial_ocr_head.conv_bn_dropout.1.weight, spatial_ocr_head.conv_bn_dropout.1.bias, spatial_ocr_head.conv_bn_dropout.1.running_mean, spatial_ocr_head.conv_bn_dropout.1.running_var, dsn_head.1.weight, dsn_head.1.bias, dsn_head.1.running_mean, dsn_head.1.running_var

_It looks like that the checkpoint model and the running model does not match at some layers. Could you take a look please? Thank you very much!_

**Comment by PkuRainBow** [comment]
@hsfzxjy

**Comment by hsfzxjy** [comment]
@iamimage Fixed. It's due to an incorrect usage of Inplace-ABN in PyTorch 1.1. The new revision should work.

**Comment by iamimage** [comment]
> @iamimage Fixed. It's due to an incorrect usage of Inplace-ABN in PyTorch 1.1. The new revision should work.

Thank you so much. It works now.  By the way,  I suspected that the following line has a typo (i changed == into in):

lib/models/tools/module_helper.py (line 104):
            elif torch_ver == ('1.0', '1.1'):

**Comment by PkuRainBow** [comment]
@iamimage Yes, you are right. We have fixed the typo.
