### ISSUE TITLE
SegFix cannot be used in my own dataset?

### ISSUE THREAD

**Issue by Sunting78** [openseg-group/openseg.pytorch#21]
SegFix is just used to citiscapes, is right? Because my own dataset hasnot the *.mat offset files.

**Comment by nigyiii** [comment]
Same question here. Can we use `scripts/cityscapes/segfix.py` to generate *.mat offset files for custom datasets?

**Comment by wujiahongPKU** [comment]
I have the same question, How to generate the offset files?  the origin offset files are for cityscapes datasets. And the Segfix paper I can not find in google or arxiv or anywhere.

**Comment by PkuRainBow** [comment]
Thanks for your interest in our work.  It requires to train the SegFix model on your own dataset that is used to predict the offset files. Currently, we have not released our paper on the arXiv and we will release the SegFix paper depending on the ECCV result.

**Comment by kotetsu-n** [comment]
Hi,
I'm really interested in using SegFix for my own dataset. The paper seems to have been released on arXiv, but do you have any plan to release the tutorial and the code to train SegFix for our own dataset? Or, if you've already released them, please let me know.

**Comment by lpengc** [comment]
Same interested in training SegFix on the CUSTOM dataset, could you please share some advice?

**Comment by PkuRainBow** [comment]
@lpengc @kotetsu-n We would like to release the training code of the SegFix on the Cityscapes & ADE20K benchmark. Especially, our SegFix can be trained with a mixture of multiple different datasets. Please stay patient.

**Comment by lpengc** [comment]
> @lpengc @kotetsu-n We would like to release the training code of the SegFix on the Cityscapes & ADE20K benchmark. Especially, our SegFix can be trained with a mixture of multiple different datasets. Please stay patient.

Another question, why use Sobel filter on the distance map can represent directions between boundary pixels and interior pixels?  Any responses would be appreciated!

**Comment by shgidi** [comment]
Same here - looking forward for the release of segfix training code.

**Comment by pocketpixels** [comment]
@PkuRainBow Congratulations on the SegFix ECCV publication! I am looking forward to the release of the model and training code. Are you planning to release your pre-trained model weights also?

**Comment by PkuRainBow** [comment]
@hsfzxjy will help to organize and release the training code and checkpoints of our SegFix method.

**Comment by pocketpixels** [comment]
@PkuRainBow @hsfzxjy Great to hear that you are planning to release checkpoints also. 

@lpengc The Sobel filter computes (an approximation to) the derivative of the distance map. And the derivative of the distance to the boundary evaluated at an image coordinate will be a 2d vector pointing to the closest point on the boundary. This is used to generate the per pixel directions in the training data. At least that is my understanding.

**Comment by PkuRainBow** [comment]
Thanks to @pocketpixels! 
@lpengc  Not exactly, the distance map records the distances between the pixel and the nearest boundary. We apply the Soble filter to estimate an offset pointing to the position with the largest distance value given a candidate sliding window.

**Comment by hsfzxjy** [comment]
@pocketpixels @shgidi
We have just released the implementation of SegFix. Please refer to https://github.com/openseg-group/openseg.pytorch/blob/master/MODEL_ZOO.md#segfix-1 for more details.

Thanks for your patience!

**Comment by hsfzxjy** [comment]
@pocketpixels @shgidi
We have just released the implementation of SegFix. Please refer to https://github.com/openseg-group/openseg.pytorch/blob/master/MODEL_ZOO.md#segfix-1 for more details.

For some reasons our result with Higher-HRNet is currently unavailable, and we provide checkpoints and script examples based on HRNet-W48. We will release them as soon as they are ready.

Thanks for your patience!

**Comment by pocketpixels** [comment]
@hsfzxjy Great, thank you! 
Are you planning to still release the training code and checkpoints for ADE20k as well? 

And do you think it could make sense to use a HRNet-W18 but with the Higher-HRNet trained transposed convolution at the end? Or would the W18 HRNet likely not have sufficient bandwidth for the higher output resolution? 
For my application I want/need the higher output resolution, but am targeting mobile, so I am constrained in terms of memory use and computational complexity.

**Comment by PkuRainBow** [comment]
@pocketpixels Currently, we have no plan to release the checkpoints for the ADE20K.  

We have released the data loader to train the unified SegFix model on multiple datasets simultaneously. Please make the related training script public. @hsfzxjy 

It might be reasonable to extend the HRNet-W18 following the https://github.com/HRNet/HigherHRNet-Human-Pose-Estimation while we have not verified such extension in the current stage.

We guess you might first verify the performance of the original HRNet-W8 and then try other advanced extensions.

Any new results on your own tasks are welcomed to be shared.

**Comment by pocketpixels** [comment]
@PkuRainBow Thank you very much for your reply.
