### ISSUE TITLE
Question on the implementation of  spatial_ocr_block.py

### ISSUE THREAD

**Issue by JialeTao** [openseg-group/openseg.pytorch#26]
Hi, noted that for spatial_ocr_block.py，this implementation is diffrent with that of your HRNet+OCR in the sub module f_object,f_pixel,f_down,f_up and so on. All the convolution layer in those sub modules are followed with a bias in this implementation, while the option 'bias' is set to 'False' in all convolution layer of those sub modules in the implementation of your HRNet+OCR. What's the motivation or different effect of the two implementation?

**Comment by PkuRainBow** [comment]
The bias has no significant influence on performance and this codebase is our original implementation.
