### ISSUE TITLE
Could you please provide the dataset preprocess script for coco-stuff dataset？

### ISSUE THREAD

**Issue by LuoYingzhao** [openseg-group/openseg.pytorch#28]
Thank you for your excellent algorithm.
Could you please provide the script that transfer the original coco-stuff dataset to the format for training？（train/image，train/label，val/image，val/label）Because I just found the scripts for other dataset（eg.cityscapes/LIP）

**Comment by PkuRainBow** [comment]
@hsfzxjy Please help to check whether we have the script for coco-stuff or the script is the same as the other benchmark.

**Comment by hsfzxjy** [comment]
@LuoYingzhao 

Script added. Please refer to https://github.com/openseg-group/openseg.pytorch/blob/master/GETTING_STARTED.md#data-preparation for instructions.

Thanks for feedback!

**Comment by LuoYingzhao** [comment]
@PkuRainBow @hsfzxjy Thanks for your script for coco-stuff, I have transferred coco-stuff successfully with your help.
Another question is about ADE20K, the data structure of original dataset do not include annotations folder described in script. So if I put all images with “ADE_train_xxxxxxxx.jpg” format in “image” folder, and put all images with “ADE_train_xxxxxxxx_seg.png” format in “label” folder, is this data transfer correct? Or there is an another transfer script for ADE20K?

**Comment by hsfzxjy** [comment]
@LuoYingzhao You might download from an alternative link  http://data.csail.mit.edu/places/ADEchallenge/ADEChallengeData2016.zip
