### ISSUE TITLE
RuntimeError: Ninja is required to load C++ extensions

### ISSUE THREAD

**Issue by Kittywyk** [openseg-group/openseg.pytorch#32]
I met this RuntimeError: Ninja is required to load C++ extensions when  the program running, could you pls help me to solve it?
Thanks a lot!
Ps, I've installed ninja and its version is 1.10.1

**Comment by PkuRainBow** [comment]
@hsfzxjy Please help to address this problem.

**Comment by hsfzxjy** [comment]
@Kittywyk hi, you can try the methods in this issue https://github.com/zhanghang1989/PyTorch-Encoding/issues/167

**Comment by Kittywyk** [comment]
> @Kittywyk hi, you can try the methods in this issue [zhanghang1989/PyTorch-Encoding#167](https://github.com/zhanghang1989/PyTorch-Encoding/issues/167)

Thank you very much.
