### ISSUE TITLE
"Default process group has not been initialized" when run scripts in model zoo

### ISSUE THREAD

**Issue by UCC-team** [openseg-group/openseg.pytorch#37]
run "bash scripts/cityscapes/hrnet/run_h_48_d_4_ocr.sh val 1". will get error as follows:

in segmentor/tester.py#L243(https://github.com/openseg-group/openseg.pytorch/blob/master/segmentor/tester.py#L243)

"Default process group has not been initialized"
AssertionError: Default process group is not initialized

**Comment by PkuRainBow** [comment]
@hsfzxjy Please help to check the reasons.

**Comment by hsfzxjy** [comment]
@UCC-team Hi. Our codebase is currently well tested under PyTorch 0.4.1. Please make sure the PyTorch version is matched.

**Comment by PkuRainBow** [comment]
@UCC-team We have supported the Pytorch 1.7.1 and achieve much better results than the reported numbers in the paper.
