### ISSUE TITLE
How to draw pictures

### ISSUE THREAD

**Issue by Klaviersonate** [openseg-group/openseg.pytorch#38]
![01](https://user-images.githubusercontent.com/51392379/95009147-5484b400-0652-11eb-9189-85392acf28f7.PNG)
![02](https://user-images.githubusercontent.com/51392379/95009150-58b0d180-0652-11eb-8d32-62945b57bb52.PNG)
![03](https://user-images.githubusercontent.com/51392379/95009156-61a1a300-0652-11eb-83f1-42fc1453613c.PNG)
Coarse Label Map，Offset Map，Refined Label Map，Distance Map， Direction Map and the last one，How to draw them。Which drawing software is used, which is a program, what is the name of the software, and can the program be open source?I want to apply Figure 2 and Figure 3 to my own grayscale map. If it can be open sourced, will it be possible in the near future?Thanks you very much.
您好，抱歉我的英语太渣了，想了解一下这3张图是如何制作的。哪些图用了画图软件，是什么软件，哪些用了程序，程序可以开源吗。我想把图2和图3应用到自己的灰度图上，如果可以开源，近期可以吗？谢谢各位大佬，万分感谢。

**Comment by PkuRainBow** [comment]
@hsfzxjy Please consider releasing the related visualization code.

**Comment by hsfzxjy** [comment]
@Klaviersonate 

 + 图一是 PowerPoint 画的
 + 图二中每个格子是写程序画的
 + 图三是写程序画的

你是想要复现上面这些图的代码，还是想要类似的代码应用在自己的数据集上（你所说的灰度图）？

**Comment by Klaviersonate** [comment]
> @Klaviersonate
> 
> * 图一是 PowerPoint 画的
> * 图二中每个格子是写程序画的
> * 图三是写程序画的
> 
> 你是想要复现上面这些图的代码，还是想要类似的代码应用在自己的数据集上（你所说的灰度图）？
> 你可以详细说说你的需求


您好，目前的想法是复现图2和图3，输入自己的一张灰度图片，通过您的程序输出图2对应的Distance Map和 Direction Map（有Binary Map程序更好，担心自己的二值化图和您程序输出的Distance Map无法匹配），以及输出图3。刚刚用PowerPoint实现了图1的画法。非常感谢您的回复。

**Comment by Klaviersonate** [comment]
> @Klaviersonate
> 
> * 图一是 PowerPoint 画的
> * 图二中每个格子是写程序画的
> * 图三是写程序画的
> 
> 你是想要复现上面这些图的代码，还是想要类似的代码应用在自己的数据集上（你所说的灰度图）？
> 你可以详细说说你的需求

您好，目前的想法是复现图2和图3，输入自己的一张灰度图片，通过您的程序输出图2对应的Binary Map、 Distance Map和 Direction Map，以及输出图3。刚刚用PowerPoint实现了图1的画法。非常感谢您的回复。

**Comment by Klaviersonate** [comment]
> @Klaviersonate
> 
> * 图一是 PowerPoint 画的
> * 图二中每个格子是写程序画的
> * 图三是写程序画的
> 
> 你是想要复现上面这些图的代码，还是想要类似的代码应用在自己的数据集上（你所说的灰度图）？
> 你可以详细说说你的需求

您好，我目前在尝试将Segfix使用到我的方法中，图2和图3不知如何实现。我有Binary Map程序，有点担心自己代码跑出来的和您程序里需要的不太一样，Distance Map是用高斯热图吗，试过没做出来。。图3一点头绪也没有。看了很多天，大佬，可以开源一下代码么，万分感谢

**Comment by PkuRainBow** [comment]
@hsfzxjy Please help him and we might consider releasing the related code soon.
