### ISSUE TITLE
Details about HRNetV2-W48 with OCR?

### ISSUE THREAD

**Issue by jihang-zhang** [openseg-group/openseg.pytorch#4]
Paper explains how you combine ResNet with OCR. The output stride of (dilated) ResNet is 8 and you use the last two stages as inputs for OCR.

However, HRNetV2 has outputs at 4 different scales (output stride = [4, 8, 16, 32]). Can you explain how you combine them?

In addition, section 3.2 in paper states that the output size of stage 3&4 are H × W. Is this 1/8 of original input image size since the output stride is 8?

**Comment by PkuRainBow** [comment]
We choose the concatenation of the 4 different scales as the input to OCR for both the region estimation and the contextual representation.

Yes, H X W is 1/8 of the input size.

**Comment by jihang-zhang** [comment]
Thanks for the reply. So I assume you use the final feature map with output stride = 4 as input to OCR?

**Comment by PkuRainBow** [comment]
Yes. output stride=4.
