### ISSUE TITLE
how to use segmix directly

### ISSUE THREAD

**Issue by yu-Mas** [openseg-group/openseg.pytorch#45]
Hi，your work are so awesome！Congratulation！
I want to progress my prediction ,would you give a simple tutorial to use Segmix directly？
Thanks for your help!
您好，我想把Segmix应用到我的模型，请问能否出个关于Segmix代码的简单使用教程吗？
万分感谢！

**Comment by PkuRainBow** [comment]
Please follow the https://github.com/openseg-group/openseg.pytorch/blob/master/MODEL_ZOO.md#refinement if you are trying to apply the SegFix to improve your Cityscapes submission.

**Comment by yu-Mas** [comment]
oh,i'm sorry that i haven't seen it.Thanks for your patient answer.Another little quetion:can i use segfix on my own dateset or other project but  not only Cityspaces？
