### ISSUE TITLE
Training stucks  every time when using 8 gpus

### ISSUE THREAD

**Issue by lubovbyc** [openseg-group/openseg.pytorch#47]
![image](https://user-images.githubusercontent.com/5144935/101334676-28381e80-38b3-11eb-828a-8e9b469f8be8.png)

Does current framework support training with 8 gpus?  Pytorch version == 0.4.1

**Comment by PkuRainBow** [comment]
Our current code base only supports 4x GPUs as the InplaceABN has bugs when trained 8x GPUs with Pytorch 0.4.1.
