### ISSUE TITLE
When will the implementation of OCR be released?

### ISSUE THREAD

**Issue by anhle-uet** [openseg-group/openseg.pytorch#5]

**Comment by PkuRainBow** [comment]
Thanks, we will release the code soon.

**Comment by dreamPoet** [comment]
Hope to see it soon. thx!!!

**Comment by PkuRainBow** [comment]
@dreamPoet Thanks for your patience. The core implementation of OCR will be firstly made open-source in the HRNet-Segmentation code base.

**Comment by dreamPoet** [comment]
Yeah that's exactly what I am waiting for... May I ask when you plan to release it?

**Comment by PkuRainBow** [comment]
We would like to notify you here once it is updated. Thanks for your patience！

**Comment by shoutOutYangJie** [comment]
please notify me too. Thank you! @PkuRainBow

**Comment by PkuRainBow** [comment]
We have released most of the code of our OCNet series and SegFix scheme. @anhle-uet @dreamPoet @shoutOutYangJie
