### ISSUE TITLE
Any plan to transplant segfix to pytorch1.x

### ISSUE THREAD

**Issue by ousinkou** [openseg-group/openseg.pytorch#50]
Pytorch0.4 is such an old version and very inconvenient to be used in a new machine. Is there any plan to transplant segfix to pytorch1.x ?

**Comment by PkuRainBow** [comment]
@ousinkou I totally agree with you but we currently have no time & GPUs to transplant to pytorch1.x~

We plan to support pytorch1.x in the future but you may try to modify it by yourself as it might require less than 100 lines of python code.

**Comment by ousinkou** [comment]
@PkuRainBow OK, thanks. I'll try it.

**Comment by PkuRainBow** [comment]
@ousinkou We have added the results of "HRNet + OCR" based on Pytorch-1.7.
