### ISSUE TITLE
Models can't match for torch1.7 branch

### ISSUE THREAD

**Issue by TiankaiHang** [openseg-group/openseg.pytorch#52]
Thanks for your nice work!
When i'm trying to use the branch pytorch1.7, i meet some problems.

For example
`bash scripts/cityscapes/hrnet/run_h_48_d_4_ocr.sh val 1`

I got
`Logging to ./log/cityscapes/hrnet_w48_ocr_1.log
2021-02-18 13:51:54,123 INFO    [offset_helper.py, 54] engery/max-distance: 5 engery/min-distance: 0
2021-02-18 13:51:54,123 INFO    [offset_helper.py, 61] direction/num_classes: 8 scale: 1
2021-02-18 13:51:54,123 INFO    [offset_helper.py, 66] c4 align axis: False
2021-02-18 13:51:54,175 INFO    [module_runner.py, 44] BN Type is torchsyncbn.
2021-02-18 13:52:06,206 INFO    [module_runner.py, 84] Loading checkpoint from ./checkpoints/cityscapes/hrnet_w48_ocr_1_latest.pth...
Traceback (most recent call last):
  File "main.py", line 217, in <module>
    model = Tester(configer)    
  File "/home/v-tihang/code_base/MyCodeBase/torch-learning/openseg.pytorch/segmentor/tester.py", line 69, in __init__
    self._init_model()
  File "/home/v-tihang/code_base/MyCodeBase/torch-learning/openseg.pytorch/segmentor/tester.py", line 73, in _init_model
    self.seg_net = self.module_runner.load_net(self.seg_net)
  File "/home/v-tihang/code_base/MyCodeBase/torch-learning/openseg.pytorch/segmentor/tools/module_runner.py", line 104, in load_net
    self.load_state_dict(net.module, checkpoint_dict, self.configer.get('network', 'resume_strict'))
  File "/home/v-tihang/code_base/MyCodeBase/torch-learning/openseg.pytorch/segmentor/tools/module_runner.py", line 156, in load_state_dict
    raise RuntimeError(err_msg)
RuntimeError: unexpected key in source state_dict: conv3x3.1.weight, conv3x3.1.bias, conv3x3.1.running_mean, conv3x3.1.running_var, ocr_distri_head.object_context_block.f_pixel.1.weight, ocr_distri_head.object_context_block.f_pixel.1.bias, ocr_distri_head.object_context_block.f_pixel.1.running_mean, ocr_distri_head.object_context_block.f_pixel.1.running_var, ocr_distri_head.object_context_block.f_pixel.3.weight, ocr_distri_head.object_context_block.f_pixel.3.bias, ocr_distri_head.object_context_block.f_pixel.3.running_mean, ocr_distri_head.object_context_block.f_pixel.3.running_var, ocr_distri_head.object_context_block.f_object.1.weight, ocr_distri_head.object_context_block.f_object.1.bias, ocr_distri_head.object_context_block.f_object.1.running_mean, ocr_distri_head.object_context_block.f_object.1.running_var, ocr_distri_head.object_context_block.f_object.3.weight, ocr_distri_head.object_context_block.f_object.3.bias, ocr_distri_head.object_context_block.f_object.3.running_mean, ocr_distri_head.object_context_block.f_object.3.running_var, ocr_distri_head.object_context_block.f_down.1.weight, ocr_distri_head.object_context_block.f_down.1.bias, ocr_distri_head.object_context_block.f_down.1.running_mean, ocr_distri_head.object_context_block.f_down.1.running_var, ocr_distri_head.object_context_block.f_up.1.weight, ocr_distri_head.object_context_block.f_up.1.bias, ocr_distri_head.object_context_block.f_up.1.running_mean, ocr_distri_head.object_context_block.f_up.1.running_var, ocr_distri_head.conv_bn_dropout.1.weight, ocr_distri_head.conv_bn_dropout.1.bias, ocr_distri_head.conv_bn_dropout.1.running_mean, ocr_distri_head.conv_bn_dropout.1.running_var, aux_head.1.weight, aux_head.1.bias, aux_head.1.running_mean, aux_head.1.running_var

missing keys in source state_dict: backbone.stage3.1.branches.0.0.bn1.num_batches_tracked, backbone.stage4.0.fuse_layers.3.2.0.1.num_batches_tracked, backbone.stage4.0.branches.3.2.bn1.num_batches_tracked, backbone.stage3.0.branches.0.1.bn1.num_batches_tracked, backbone.stage4.1.branches.0.1.bn1.num_batches_tracked, backbone.stage3.0.branches.1.3.bn1.num_batches_tracked, backbone.stage4.1.branches.3.2.bn1.num_batches_tracked, backbone.stage3.2.fuse_layers.2.0.0.1.num_batches_tracked, backbone.stage3.1.branches.2.2.bn1.num_batches_tracked, backbone.stage4.0.branches.3.1.bn2.num_batches_tracked, backbone.stage3.3.branches.1.2.bn2.num_batches_tracked, backbone.layer1.0.downsample.1.num_batches_tracked, backbone.stage4.1.branches.2.1.bn1.num_batches_tracked, backbone.stage4.2.fuse_layers.0.1.1.num_batches_tracked, backbone.stage4.0.branches.1.0.bn2.num_batches_tracked, backbone.layer1.0.bn2.num_batches_tracked, backbone.stage4.1.branches.1.2.bn1.num_batches_tracked, backbone.stage3.2.branches.2.1.bn2.num_batches_tracked, backbone.stage2.0.branches.0.2.bn1.num_batches_tracked, aux_head.1.0.running_var, backbone.stage3.0.branches.0.3.bn2.num_batches_tracked, backbone.stage4.1.branches.1.0.bn2.num_batches_tracked, backbone.stage4.0.fuse_layers.3.0.2.1.num_batches_tracked, backbone.stage4.2.branches.2.0.bn1.num_batches_tracked, backbone.stage3.3.fuse_layers.2.0.1.1.num_batches_tracked, backbone.stage3.0.branches.2.0.bn1.num_batches_tracked, backbone.stage4.2.branches.2.3.bn2.num_batches_tracked, backbone.stage3.1.branches.2.0.bn2.num_batches_tracked, backbone.stage2.0.branches.1.2.bn1.num_batches_tracked, backbone.layer1.3.bn2.num_batches_tracked, backbone.stage3.3.branches.0.2.bn1.num_batches_tracked, backbone.stage4.1.branches.1.2.bn2.num_batches_tracked, backbone.stage3.2.branches.1.0.bn2.num_batches_tracked, backbone.stage3.0.fuse_layers.2.1.0.1.num_batches_tracked, backbone.stage3.1.branches.0.2.bn1.num_batches_tracked, backbone.stage3.1.branches.1.1.bn1.num_batches_tracked, backbone.stage4.1.branches.3.3.bn1.num_batches_tracked, backbone.layer1.3.bn1.num_batches_tracked, backbone.stage3.2.branches.2.2.bn1.num_batches_tracked, backbone.stage4.2.branches.0.3.bn1.num_batches_tracked, backbone.stage4.2.fuse_layers.3.1.1.1.num_batches_tracked, backbone.layer1.1.bn1.num_batches_tracked, backbone.stage2.0.branches.1.1.bn2.num_batches_tracked, backbone.stage3.2.branches.2.0.bn1.num_batches_tracked, conv3x3.1.0.weight, backbone.stage4.1.fuse_layers.3.2.0.1.num_batches_tracked, ocr_distri_head.object_context_block.f_down.1.0.bias, backbone.stage3.0.branches.0.3.bn1.num_batches_tracked, backbone.stage3.2.branches.1.1.bn1.num_batches_tracked, backbone.stage3.3.branches.1.3.bn2.num_batches_tracked, aux_head.1.0.num_batches_tracked, backbone.stage4.2.branches.2.1.bn1.num_batches_tracked, backbone.stage4.0.branches.0.2.bn1.num_batches_tracked, backbone.stage4.0.branches.3.3.bn2.num_batches_tracked, backbone.stage4.1.branches.2.0.bn1.num_batches_tracked, backbone.stage4.1.branches.2.3.bn1.num_batches_tracked, backbone.stage4.0.branches.1.0.bn1.num_batches_tracked, backbone.stage3.1.fuse_layers.2.0.0.1.num_batches_tracked, ocr_distri_head.conv_bn_dropout.1.0.bias, backbone.stage2.0.branches.1.0.bn2.num_batches_tracked, backbone.stage4.1.branches.0.3.bn2.num_batches_tracked, backbone.stage4.2.fuse_layers.3.0.1.1.num_batches_tracked, backbone.stage3.1.fuse_layers.2.1.0.1.num_batches_tracked, backbone.stage4.0.branches.0.1.bn1.num_batches_tracked, backbone.stage4.1.fuse_layers.0.3.1.num_batches_tracked, backbone.stage3.2.branches.0.1.bn1.num_batches_tracked, backbone.stage3.2.branches.0.2.bn1.num_batches_tracked, backbone.stage4.2.branches.2.0.bn2.num_batches_tracked, backbone.stage3.3.fuse_layers.0.1.1.num_batches_tracked, backbone.stage3.3.branches.1.3.bn1.num_batches_tracked, backbone.stage3.0.branches.2.1.bn2.num_batches_tracked, backbone.stage4.2.branches.0.1.bn1.num_batches_tracked, backbone.stage4.1.branches.0.0.bn2.num_batches_tracked, backbone.stage3.0.fuse_layers.2.0.1.1.num_batches_tracked, backbone.stage4.0.fuse_layers.2.3.1.num_batches_tracked, backbone.stage4.0.fuse_layers.3.1.1.1.num_batches_tracked, backbone.stage4.2.branches.3.0.bn1.num_batches_tracked, backbone.stage4.0.branches.3.1.bn1.num_batches_tracked, backbone.stage4.1.branches.0.2.bn1.num_batches_tracked, backbone.stage3.3.fuse_layers.2.1.0.1.num_batches_tracked, backbone.stage4.2.branches.3.3.bn2.num_batches_tracked, backbone.stage3.1.fuse_layers.1.2.1.num_batches_tracked, backbone.stage4.1.fuse_layers.0.1.1.num_batches_tracked, backbone.stage4.1.fuse_layers.2.1.0.1.num_batches_tracked, backbone.stage3.2.branches.0.1.bn2.num_batches_tracked, backbone.stage4.2.branches.1.0.bn2.num_batches_tracked, backbone.stage4.0.branches.2.2.bn2.num_batches_tracked, ocr_distri_head.object_context_block.f_up.1.0.weight, backbone.stage2.0.branches.1.3.bn1.num_batches_tracked, backbone.stage3.1.branches.1.0.bn1.num_batches_tracked, backbone.stage3.3.branches.2.1.bn1.num_batches_tracked, backbone.stage2.0.branches.1.3.bn2.num_batches_tracked, backbone.stage3.2.fuse_layers.1.2.1.num_batches_tracked, backbone.stage3.2.fuse_layers.1.0.0.1.num_batches_tracked, backbone.stage3.2.branches.1.1.bn2.num_batches_tracked, ocr_distri_head.object_context_block.f_pixel.3.0.num_batches_tracked, backbone.stage4.1.branches.2.2.bn2.num_batches_tracked, backbone.stage3.1.branches.1.3.bn1.num_batches_tracked, backbone.stage3.2.branches.2.3.bn2.num_batches_tracked, backbone.stage4.0.fuse_layers.2.0.1.1.num_batches_tracked, backbone.stage3.1.branches.1.0.bn2.num_batches_tracked, ocr_distri_head.object_context_block.f_up.1.0.num_batches_tracked, backbone.stage4.1.fuse_layers.3.0.2.1.num_batches_tracked, ocr_distri_head.object_context_block.f_object.1.0.num_batches_tracked, backbone.stage4.2.branches.0.2.bn2.num_batches_tracked, backbone.stage3.1.branches.0.3.bn2.num_batches_tracked, backbone.stage3.2.branches.1.0.bn1.num_batches_tracked, backbone.stage3.3.branches.0.1.bn2.num_batches_tracked, backbone.stage4.0.fuse_layers.3.0.1.1.num_batches_tracked, backbone.stage4.1.branches.3.1.bn1.num_batches_tracked, backbone.stage4.2.branches.1.2.bn1.num_batches_tracked, backbone.stage4.2.fuse_layers.1.2.1.num_batches_tracked, backbone.stage4.2.branches.0.0.bn2.num_batches_tracked, backbone.stage2.0.branches.0.0.bn2.num_batches_tracked, backbone.stage4.2.fuse_layers.1.3.1.num_batches_tracked, ocr_distri_head.object_context_block.f_pixel.1.0.running_var, backbone.stage4.0.branches.1.1.bn1.num_batches_tracked, backbone.stage3.0.branches.0.2.bn1.num_batches_tracked, backbone.stage4.2.branches.0.2.bn1.num_batches_tracked, backbone.stage3.0.branches.0.1.bn2.num_batches_tracked, backbone.stage4.2.branches.1.3.bn1.num_batches_tracked, backbone.stage3.2.branches.2.1.bn1.num_batches_tracked, backbone.stage3.0.branches.2.3.bn1.num_batches_tracked, backbone.stage3.1.branches.2.2.bn2.num_batches_tracked, backbone.stage3.1.branches.0.1.bn2.num_batches_tracked, backbone.stage3.2.branches.1.2.bn1.num_batches_tracked, backbone.stage3.0.branches.1.1.bn2.num_batches_tracked, backbone.stage4.1.branches.1.3.bn2.num_batches_tracked, ocr_distri_head.object_context_block.f_pixel.1.0.running_mean, backbone.stage3.1.branches.1.3.bn2.num_batches_tracked, backbone.stage4.1.fuse_layers.2.0.1.1.num_batches_tracked, ocr_distri_head.conv_bn_dropout.1.0.weight, backbone.transition3.3.0.1.num_batches_tracked, backbone.stage4.1.branches.3.0.bn1.num_batches_tracked, ocr_distri_head.object_context_block.f_down.1.0.running_var, backbone.stage4.1.branches.2.0.bn2.num_batches_tracked, backbone.stage3.2.fuse_layers.2.0.1.1.num_batches_tracked, backbone.stage4.1.branches.3.0.bn2.num_batches_tracked, ocr_distri_head.object_context_block.f_pixel.1.0.weight, aux_head.1.0.weight, backbone.layer1.1.bn2.num_batches_tracked, backbone.stage3.1.branches.2.3.bn1.num_batches_tracked, backbone.stage4.2.branches.3.0.bn2.num_batches_tracked, ocr_distri_head.object_context_block.f_pixel.3.0.weight, ocr_distri_head.object_context_block.f_object.3.0.num_batches_tracked, backbone.stage3.2.fuse_layers.0.2.1.num_batches_tracked, backbone.stage4.1.branches.3.1.bn2.num_batches_tracked, backbone.stage3.2.branches.0.2.bn2.num_batches_tracked, backbone.stage2.0.branches.0.1.bn2.num_batches_tracked, backbone.layer1.0.bn3.num_batches_tracked, backbone.stage3.3.branches.2.3.bn2.num_batches_tracked, backbone.stage4.1.branches.3.2.bn2.num_batches_tracked, backbone.stage4.2.branches.3.1.bn1.num_batches_tracked, backbone.stage3.2.branches.0.0.bn1.num_batches_tracked, backbone.stage4.1.fuse_layers.3.1.1.1.num_batches_tracked, backbone.stage4.1.branches.1.1.bn2.num_batches_tracked, backbone.stage4.0.branches.2.3.bn2.num_batches_tracked, backbone.stage4.2.branches.3.2.bn2.num_batches_tracked, ocr_distri_head.object_context_block.f_down.1.0.weight, backbone.stage4.1.branches.2.1.bn2.num_batches_tracked, backbone.stage4.1.fuse_layers.1.0.0.1.num_batches_tracked, backbone.stage4.0.branches.1.2.bn2.num_batches_tracked, backbone.stage3.3.branches.0.0.bn1.num_batches_tracked, backbone.stage4.0.fuse_layers.3.1.0.1.num_batches_tracked, backbone.transition1.1.0.1.num_batches_tracked, backbone.stage4.2.branches.3.2.bn1.num_batches_tracked, backbone.stage4.2.fuse_layers.2.0.1.1.num_batches_tracked, backbone.stage2.0.branches.0.0.bn1.num_batches_tracked, backbone.layer1.0.bn1.num_batches_tracked, backbone.stage3.0.fuse_layers.1.2.1.num_batches_tracked, backbone.stage3.3.branches.1.2.bn1.num_batches_tracked, ocr_distri_head.object_context_block.f_up.1.0.running_var, backbone.stage4.1.branches.0.2.bn2.num_batches_tracked, backbone.stage3.3.fuse_layers.1.0.0.1.num_batches_tracked, backbone.stage4.2.branches.3.3.bn1.num_batches_tracked, backbone.stage3.3.fuse_layers.1.2.1.num_batches_tracked, backbone.stage3.3.branches.2.2.bn2.num_batches_tracked, backbone.stage3.0.branches.1.2.bn1.num_batches_tracked, backbone.stage3.0.fuse_layers.0.1.1.num_batches_tracked, backbone.stage4.0.branches.3.3.bn1.num_batches_tracked, backbone.transition2.2.0.1.num_batches_tracked, backbone.stage4.2.branches.1.1.bn2.num_batches_tracked, backbone.stage4.2.branches.2.2.bn2.num_batches_tracked, backbone.stage4.0.branches.2.0.bn1.num_batches_tracked, backbone.stage4.1.fuse_layers.3.0.0.1.num_batches_tracked, ocr_distri_head.object_context_block.f_pixel.1.0.num_batches_tracked, backbone.stage4.2.fuse_layers.3.2.0.1.num_batches_tracked, backbone.stage4.0.fuse_layers.2.1.0.1.num_batches_tracked, conv3x3.1.0.bias, backbone.stage3.1.fuse_layers.2.0.1.1.num_batches_tracked, aux_head.1.0.running_mean, backbone.stage4.2.fuse_layers.2.3.1.num_batches_tracked, ocr_distri_head.object_context_block.f_pixel.3.0.running_mean, backbone.stage4.0.branches.2.1.bn1.num_batches_tracked, backbone.stage3.3.branches.0.0.bn2.num_batches_tracked, backbone.stage4.1.branches.1.3.bn1.num_batches_tracked, backbone.stage3.0.branches.2.0.bn2.num_batches_tracked, aux_head.1.0.bias, backbone.stage3.3.branches.1.1.bn2.num_batches_tracked, backbone.stage3.3.fuse_layers.0.2.1.num_batches_tracked, backbone.stage4.0.branches.0.0.bn1.num_batches_tracked, backbone.stage4.1.fuse_layers.2.3.1.num_batches_tracked, backbone.layer1.3.bn3.num_batches_tracked, backbone.stage4.1.branches.0.3.bn1.num_batches_tracked, ocr_distri_head.object_context_block.f_object.1.0.bias, backbone.stage3.1.fuse_layers.0.2.1.num_batches_tracked, backbone.stage3.0.fuse_layers.2.0.0.1.num_batches_tracked, ocr_distri_head.object_context_block.f_pixel.3.0.running_var, backbone.stage3.3.branches.2.1.bn2.num_batches_tracked, backbone.stage4.1.fuse_layers.1.3.1.num_batches_tracked, ocr_distri_head.object_context_block.f_object.3.0.weight, ocr_distri_head.object_context_block.f_pixel.3.0.bias, backbone.stage3.3.branches.1.0.bn2.num_batches_tracked, backbone.stage4.1.fuse_layers.2.0.0.1.num_batches_tracked, backbone.stage4.0.branches.0.2.bn2.num_batches_tracked, ocr_distri_head.object_context_block.f_object.3.0.bias, backbone.stage4.0.branches.2.2.bn1.num_batches_tracked, backbone.stage3.3.branches.1.0.bn1.num_batches_tracked, ocr_distri_head.conv_bn_dropout.1.0.running_mean, ocr_distri_head.object_context_block.f_object.3.0.running_mean, backbone.stage4.1.fuse_layers.3.1.0.1.num_batches_tracked, conv3x3.1.0.running_var, backbone.stage3.0.branches.2.2.bn2.num_batches_tracked, backbone.stage3.3.branches.0.3.bn2.num_batches_tracked, backbone.stage3.0.branches.1.0.bn1.num_batches_tracked, backbone.stage4.1.branches.1.1.bn1.num_batches_tracked, backbone.stage4.0.fuse_layers.0.1.1.num_batches_tracked, backbone.stage4.2.branches.1.0.bn1.num_batches_tracked, backbone.stage4.0.branches.3.0.bn2.num_batches_tracked, ocr_distri_head.object_context_block.f_object.1.0.weight, backbone.stage4.1.fuse_layers.0.2.1.num_batches_tracked, backbone.stage3.1.branches.1.2.bn2.num_batches_tracked, backbone.stage3.0.fuse_layers.1.0.0.1.num_batches_tracked, backbone.stage4.0.branches.2.1.bn2.num_batches_tracked, backbone.stage3.1.branches.2.1.bn2.num_batches_tracked, backbone.stage2.0.branches.1.0.bn1.num_batches_tracked, backbone.stage4.2.fuse_layers.3.1.0.1.num_batches_tracked, backbone.stage4.2.fuse_layers.2.1.0.1.num_batches_tracked, backbone.stage4.2.branches.2.1.bn2.num_batches_tracked, ocr_distri_head.object_context_block.f_object.1.0.running_mean, backbone.stage4.2.fuse_layers.3.0.2.1.num_batches_tracked, backbone.stage3.0.fuse_layers.0.2.1.num_batches_tracked, backbone.stage4.0.branches.1.2.bn1.num_batches_tracked, backbone.stage4.1.branches.0.1.bn2.num_batches_tracked, backbone.stage3.3.branches.2.0.bn2.num_batches_tracked, backbone.stage2.0.branches.0.3.bn1.num_batches_tracked, backbone.stage3.3.branches.0.3.bn1.num_batches_tracked, backbone.stage3.0.branches.2.3.bn2.num_batches_tracked, backbone.stage3.2.branches.1.3.bn2.num_batches_tracked, backbone.stage3.1.fuse_layers.1.0.0.1.num_batches_tracked, backbone.stage3.1.branches.2.3.bn2.num_batches_tracked, backbone.stage3.2.branches.1.2.bn2.num_batches_tracked, backbone.stage3.3.branches.2.2.bn1.num_batches_tracked, backbone.stage2.0.branches.0.1.bn1.num_batches_tracked, backbone.stage3.1.branches.1.1.bn2.num_batches_tracked, backbone.stage3.3.branches.0.1.bn1.num_batches_tracked, backbone.stage3.1.branches.0.2.bn2.num_batches_tracked, backbone.layer1.2.bn1.num_batches_tracked, backbone.stage3.2.branches.0.0.bn2.num_batches_tracked, backbone.stage4.0.fuse_layers.0.3.1.num_batches_tracked, backbone.stage4.0.branches.0.0.bn2.num_batches_tracked, backbone.stage4.0.branches.0.3.bn2.num_batches_tracked, backbone.stage4.2.branches.0.3.bn2.num_batches_tracked, backbone.stage4.0.branches.3.0.bn1.num_batches_tracked, backbone.stage3.3.fuse_layers.2.0.0.1.num_batches_tracked, backbone.stage4.2.fuse_layers.2.0.0.1.num_batches_tracked, backbone.layer1.2.bn3.num_batches_tracked, backbone.stage2.0.branches.0.3.bn2.num_batches_tracked, backbone.stage4.0.fuse_layers.1.3.1.num_batches_tracked, backbone.stage2.0.fuse_layers.1.0.0.1.num_batches_tracked, backbone.stage3.1.branches.2.0.bn1.num_batches_tracked, backbone.stage4.2.branches.2.3.bn1.num_batches_tracked, backbone.stage3.2.fuse_layers.0.1.1.num_batches_tracked, backbone.layer1.1.bn3.num_batches_tracked, backbone.stage3.1.branches.0.3.bn1.num_batches_tracked, ocr_distri_head.object_context_block.f_down.1.0.running_mean, backbone.stage4.1.fuse_layers.1.2.1.num_batches_tracked, backbone.stage4.2.branches.0.1.bn2.num_batches_tracked, backbone.layer1.2.bn2.num_batches_tracked, backbone.stage3.1.branches.2.1.bn1.num_batches_tracked, backbone.stage4.0.branches.2.3.bn1.num_batches_tracked, backbone.stage3.1.branches.1.2.bn1.num_batches_tracked, backbone.stage3.2.branches.0.3.bn2.num_batches_tracked, backbone.stage3.1.branches.0.1.bn1.num_batches_tracked, backbone.stage4.2.branches.1.3.bn2.num_batches_tracked, backbone.stage4.1.branches.0.0.bn1.num_batches_tracked, conv3x3.1.0.num_batches_tracked, backbone.stage3.0.branches.0.2.bn2.num_batches_tracked, ocr_distri_head.object_context_block.f_up.1.0.running_mean, backbone.stage4.2.fuse_layers.0.3.1.num_batches_tracked, backbone.stage4.1.branches.2.2.bn1.num_batches_tracked, backbone.stage3.1.fuse_layers.0.1.1.num_batches_tracked, backbone.stage4.1.branches.3.3.bn2.num_batches_tracked, backbone.stage3.2.branches.0.3.bn1.num_batches_tracked, backbone.stage2.0.fuse_layers.0.1.1.num_batches_tracked, backbone.stage3.3.branches.1.1.bn1.num_batches_tracked, backbone.stage3.0.branches.0.0.bn2.num_batches_tracked, backbone.stage4.0.fuse_layers.1.0.0.1.num_batches_tracked, ocr_distri_head.object_context_block.f_object.3.0.running_var, backbone.stage4.2.branches.3.1.bn2.num_batches_tracked, backbone.stage4.0.branches.3.2.bn2.num_batches_tracked, ocr_distri_head.object_context_block.f_down.1.0.num_batches_tracked, backbone.stage4.0.branches.0.3.bn1.num_batches_tracked, backbone.stage4.2.branches.2.2.bn1.num_batches_tracked, backbone.stage4.0.branches.1.1.bn2.num_batches_tracked, backbone.stage3.3.branches.2.0.bn1.num_batches_tracked, backbone.stage4.2.branches.0.0.bn1.num_batches_tracked, backbone.stage4.1.branches.1.0.bn1.num_batches_tracked, backbone.stage2.0.branches.1.2.bn2.num_batches_tracked, backbone.stage3.3.branches.2.3.bn1.num_batches_tracked, backbone.stage3.0.branches.1.3.bn2.num_batches_tracked, backbone.stage4.1.fuse_layers.3.0.1.1.num_batches_tracked, backbone.stage3.2.fuse_layers.2.1.0.1.num_batches_tracked, ocr_distri_head.conv_bn_dropout.1.0.running_var, backbone.stage4.2.fuse_layers.1.0.0.1.num_batches_tracked, backbone.bn2.num_batches_tracked, backbone.stage3.0.branches.2.1.bn1.num_batches_tracked, backbone.bn1.num_batches_tracked, backbone.stage3.1.branches.0.0.bn2.num_batches_tracked, conv3x3.1.0.running_mean, backbone.stage4.0.branches.0.1.bn2.num_batches_tracked, backbone.stage4.0.branches.2.0.bn2.num_batches_tracked, backbone.stage4.0.fuse_layers.2.0.0.1.num_batches_tracked, backbone.stage4.2.branches.1.1.bn1.num_batches_tracked, ocr_distri_head.conv_bn_dropout.1.0.num_batches_tracked, ocr_distri_head.object_context_block.f_up.1.0.bias, ocr_distri_head.object_context_block.f_pixel.1.0.bias, backbone.stage4.1.branches.2.3.bn2.num_batches_tracked, backbone.stage4.0.fuse_layers.1.2.1.num_batches_tracked, backbone.stage2.0.branches.1.1.bn1.num_batches_tracked, backbone.stage3.2.branches.2.3.bn1.num_batches_tracked, backbone.stage3.0.branches.1.1.bn1.num_batches_tracked, backbone.stage4.0.branches.1.3.bn2.num_batches_tracked, backbone.stage3.0.branches.1.2.bn2.num_batches_tracked, backbone.stage3.0.branches.2.2.bn1.num_batches_tracked, backbone.stage4.0.branches.1.3.bn1.num_batches_tracked, backbone.stage4.0.fuse_layers.0.2.1.num_batches_tracked, backbone.stage4.2.fuse_layers.3.0.0.1.num_batches_tracked, backbone.stage3.2.branches.2.2.bn2.num_batches_tracked, backbone.transition1.0.1.num_batches_tracked, backbone.stage3.3.branches.0.2.bn2.num_batches_tracked, backbone.stage3.0.branches.1.0.bn2.num_batches_tracked, backbone.stage4.2.fuse_layers.0.2.1.num_batches_tracked, backbone.stage3.2.branches.1.3.bn1.num_batches_tracked, backbone.stage3.2.branches.2.0.bn2.num_batches_tracked, backbone.stage2.0.branches.0.2.bn2.num_batches_tracked, ocr_distri_head.object_context_block.f_object.1.0.running_var, backbone.stage3.0.branches.0.0.bn1.num_batches_tracked, backbone.stage4.0.fuse_layers.3.0.0.1.num_batches_tracked, backbone.stage4.2.branches.1.2.bn2.num_batches_tracked

evaluate the result...
ERROR: Cannot find any ground truth images to use for evaluation. Searched for: /cityscapes/val/label/*.png`

**Comment by PkuRainBow** [comment]
@TiankaiHang Thanks for your interest in our work. All the released checkpoints are previously trained with pytorch-0.4.1.
We will the main checkpoints based on pytorch-1.7 very soon.

**Comment by TiankaiHang** [comment]
> @TiankaiHang Thanks for your interest in our work. All the released checkpoints are previously trained with pytorch-0.4.1.
> We will the main checkpoints based on pytorch-1.7 very soon.

thanks :-)

**Comment by PkuRainBow** [comment]
If you have access to 8x GPUs, it is very easy to reproduce the 83+ performance based on the https://github.com/openseg-group/openseg.pytorch/blob/pytorch-1.7/scripts/cityscapes/hrnet/run_h_48_d_4_ocr_rmi_paddle.sh within several hours.
