### ISSUE TITLE
CRF parameters used in the ablation study of SegFix paper

### ISSUE THREAD

**Issue by jfzhuang** [openseg-group/openseg.pytorch#53]
Thanks for your excellent work. I want to reproduce your experimental results in the comparison with DenseCRF in the SegFix paper. However, I can not find an appropriate group of parameters. It will be very helpful if you can provide the parameters used in your experiments. Thanks a lot!

**Comment by PkuRainBow** [comment]
Thanks for your interest. @hsfzxjy Please help to release the DenseCRF related code.
