### ISSUE TITLE
Some problems about ohem loss

### ISSUE THREAD

**Issue by ydhongHIT** [openseg-group/openseg.pytorch#57]
![A4`5}Y`2U)8E@(GMTN7$LX0](https://user-images.githubusercontent.com/42939497/109824310-abc79880-7c73-11eb-976c-e4d23e42be63.png)

As shown in the picture, I didn't understand why the training suddenly ends. Could you provide some advices? Thanks.

**Comment by PkuRainBow** [comment]
@hsfzxjy  Please help address this problem~ This seems like the previous errors we meet on the ADE20K training.

**Comment by hsfzxjy** [comment]
@ydhongHIT It's an innate flaw in the current OHEM implementation. We've fixed it in [the lastest commit](https://github.com/openseg-group/openseg.pytorch/commit/cefe8b7e27dd8fae6281559bc2f8ac90e505f191) (on both branches). You can pull down the repo and try again~
