### ISSUE TITLE
Excuse me, I want to ask how to execute this step in "Getting Started with openseg.pytorch.md", thank you!

### ISSUE THREAD

**Issue by tiesanguaixia** [openseg-group/openseg.pytorch#60]
**Data Preparation**
You need to download Cityscapes, LIP, PASCAL-Context or COCO-Stuff 10k v1.1 datasets.
We arrange images and labels in another way. You could preprocess the files by running:

`python lib/datasets/preprocess/cityscapes/cityscapes_generator.py --coarse True \
  --save_dir <path/to/preprocessed_cityscapes> --ori_root_dir <path/to/original_cityscapes>
python lib/datasets/preprocess/pascal_context/pascal_context_generator.py \
  --save_dir <path/to/preprocessed_context> --ori_root_dir <path/to/original_context>
python lib/datasets/preprocess/coco_stuff/coco_stuff_generator.py \
  --save_dir <path/to/preprocessed_cocostuff> --ori_root_dir <path/to/original_cocostuff>`

After I ran these 3 types of code, I always received an error:
**/bin/sh: 1:Syntax error: end of file unexpected.**

Do you know how to handle it and go ahead to run your entire code? Thank you!

**Comment by hsfzxjy** [comment]
@tiesanguaixia You should replace content within `<...>` to some real path.
