### ISSUE TITLE
confusion about the data for segfix

### ISSUE THREAD

**Issue by dadada101** [openseg-group/openseg.pytorch#63]
hi,  @PkuRainBow  @hsfzxjy  @LayneH 
  for the purpose of training the segfix on  the cityscapes dataset, it seems you used the coarse label file to train the model see below（i.e. model for predicting the boundary and direction)? but In my understanding , this model should be trained by the fine labeled mask?
it is right? if not , how can the trained segfix model be able to give accurate boundary and direction , therefore seems impossible to get the good fixed result on the coarse mask prediction by some segmenation model.

in https://github.com/openseg-group/openseg.pytorch/blob/master/GETTING_STARTED.md, Data Preparation part shows:
python lib/datasets/preprocess/cityscapes/cityscapes_generator.py --coarse True \
  --save_dir <path/to/preprocessed_cityscapes> --ori_root_dir <path/to/original_cityscapes>
python lib/datasets/preprocess/pascal_context/pascal_context_generator.py \
  --save_dir <path/to/preprocessed_context> --ori_root_dir <path/to/original_context>
python lib/datasets/preprocess/coco_stuff/coco_stuff_generator.py \
  --save_dir <path/to/preprocessed_cocostuff> --ori_root_dir <path/to/original_cocostuff>

the ' --coarse True ' indicates  coarse label used.

**Comment by hsfzxjy** [comment]
@dadada101 The script cityscapes_generator.py simply pre-processes all label files in Cityscapes. SegFix doesn't use any coarse label files. Coarse labels are used in training state-of-the-arts OCR models.

**Comment by dadada101** [comment]
thanks a lot
