### ISSUE TITLE
The link of  offset_semantic.zip do not work.

### ISSUE THREAD

**Issue by DLUT-yyc** [openseg-group/openseg.pytorch#66]
In MODEL_ZOO.md, the link of  offset_semantic.zip in SegFix do not work:

SegFix
On Cityscapes, we can use SegFix scheme to further refine the boundary of segmentation results. To apply SegFix, you should first download **_offset_semantic.zip_** to $DATA_ROOT/cityscapes, then unzip the archive. Take HRNet-W48 based OCR as an example. To refine the results on Cityscapes val set, you should first run bash scripts/cityscapes/hrnet/run_h_48_d_4_ocr.sh val 1 to obtain the baseline results, then run bash scripts/cityscapes/hrnet/run_h_48_d_4_ocr.sh segfix 1 val to apply SegFix.
Thanks for your early reply~

**Comment by hsfzxjy** [comment]
Fixed. Thanks for feedback!
