### ISSUE TITLE
Some broken links for checkpoints in MODEL ZOO

### ISSUE THREAD

**Issue by rawalkhirodkar** [openseg-group/openseg.pytorch#68]
Thank you for your work.
Some of the model links in the model zoo are broken. (say COCO-stuff, OCR + RMI).
Is it possible to fix this? Thanks.

![image](https://user-images.githubusercontent.com/8392905/120258743-9d801d00-c260-11eb-824c-a23ccbd0190f.png)

**Comment by PkuRainBow** [comment]
@rawalkhirodkar Thanks for your interest in our work~

We will add the links to the checkpoints & logs soon.
