### ISSUE TITLE
Pytorch-1.7 checkpoints?

### ISSUE THREAD

**Issue by adwiii** [openseg-group/openseg.pytorch#74]
[This commit](https://github.com/openseg-group/openseg.pytorch/commit/429a0da76361dc407aa4a8953acf769e81457aef#diff-7704cc4bd485c272f9171f0047f1c064063395172ae58c3c9aacd36fc7f50261) notes that the supplied checkpoints in the [model zoo](https://github.com/openseg-group/openseg.pytorch/blob/pytorch-1.7/MODEL_ZOO.md) are trained using 0.4.1 and that 1.7 will be released soon. Is there a timeline to release the checkpoints for Pytorch-1.7?

**Comment by PkuRainBow** [comment]
@adwiii Thanks for your interest in our work!

We will update the code and support HRNet + Transformer architecture.  The related checkpoints based on PaddlePaddle version will also be included then.

**Comment by Italy2006** [comment]
> @adwiii Thanks for your interest in our work!
> 
> We will update the code and support HRNet + Transformer architecture. The related checkpoints based on PaddlePaddle version will also be included then.

But for scripts/cityscapes/hrnet/run_h_48_d_4_ocr.sh, I found that its model is still torch0.4.0，When are you free to update?
