### ISSUE TITLE
When will the checkpoint of OCR+RMI+paddle released?

### ISSUE THREAD

**Issue by ffff123ffff** [openseg-group/openseg.pytorch#77]
I want to use the model OCR+RMI+paddle which achieves 58.21% on LIP. When will it be released?
Thanks!

**Comment by PkuRainBow** [comment]
@ffff123ffff Thanks for your interest in our work.

In fact, we are busy on new projects and I highly encourage you to reproduce the results.

I also would like to polish the code and release the related logs and checkpoints ASAP.

**Comment by ffff123ffff** [comment]
Thanks for your kind reply and I will reproduce the results.

**Comment by PkuRainBow** [comment]
Please check the latest commit. @ffff123ffff
