### ISSUE TITLE
segfix offsets

### ISSUE THREAD

**Issue by marcok** [openseg-group/openseg.pytorch#8]
Hi thanks for releasing the code, first thing was to try it by myself!

All worked very well, i successfully trained and validated with own images and own label files.
But what I don't get is, how I can generate own *.mat files to run the segfix. You provided only mat files for cityscape but how to generate them for an own dataset?

When starting val with segfix (scripts/cityscapes/hrnet/run_h_48_d_4_ocr.sh segfix 3 val) I recieve:

FileNotFoundError: [Errno 2] No such file or directory: openseg.pytorch/data/cityscapes/val/offset_pred/semantic/offset_hrnext/is-03-08-2019-normal-98-001089.mat'

**Comment by PkuRainBow** [comment]
Thanks for your interest in our work!

Currently, we have not released the checkpoints of the SegFix model and we will notify you once released. We mainly release the offsets for Cityscapes as this is one of the most challenging benchmarks and the SegFix offsets generalize well across various baseline methods.

**Comment by marcok** [comment]
Thanks for answer.

I'm not sure if I understand.
In your Zip File you have a .mat file for each val label file in cityscape offset_semantic\val\offset_pred\semantic\offset_hrnext
which I assume will only work for particular this label file.

Does it mean as soon as you released the SegFix model it will be possible to generate a mat file by a second prediction (additional to the label file prediction from hrnet), after that it has to be applied by segfix.py?

Or in other words, currently your SegFix approach can only be validated with exactly the same label files e.g. frankfurt_000000_000576_leftImg8bit.png?

**Comment by PkuRainBow** [comment]
Yes, we need to predict the image-dependent offset files. In other words, our SegFix takes only the input image and generates the offset file for each image adaptively.

**Comment by marcok** [comment]
Thanks, now all clear. Waiting patently for the segfix model release then.

**Comment by qingchengboy** [comment]
@marcok hi,How do you generate offset data (.mat) on your own data,:)
