### ISSUE TITLE
inplace_abn

### ISSUE THREAD

**Issue by qqqlz** [openseg-group/openseg.pytorch#9]
Thanks for your job!
elif torch_ver == '1.2':
                from inplace_abn import InPlaceABNSync
                return InPlaceABNSync(num_features, **kwargs)
I cant't find the file of inplace_abn for torch_ver==1.2
and i want to know if i use this file if i need to install first

**Comment by PkuRainBow** [comment]
In fact, you do not need to install it. 

Besides, all of our implementations are mainly developed with Pytorch.0.4.1 and you might need to train the models for more epochs with Pytorch1.2 according to your previous observation.

**Comment by qqqlz** [comment]
Sorry, to bother you again.
I still don't find the 

elif torch_ver == '1.2':
from inplace_abn import InPlaceABNSync
return InPlaceABNSync(num_features, **kwargs)
in your code

where is the inplace_abn ,you mention above?

**Comment by PkuRainBow** [comment]
@qqqlz Yes, you are right. We used to install the inplace-abn (added to the default python path) for Pytorch 1.2 following the instructions in https://github.com/mapillary/inplace_abn.

**Comment by QuentinAI** [comment]
> Sorry, to bother you again.
> I still don't find the
> 
> elif torch_ver == '1.2':
> from inplace_abn import InPlaceABNSync
> return InPlaceABNSync(num_features, **kwargs)
> in your code
> 
> where is the inplace_abn ,you mention above?

Have you solved the problem? I met the same problem with torch.__ver__==1.2. I don't know how to combine the instructions in  https://github.com/mapillary/inplace_abn with the openseg codes.
